### ISSUE TITLE
OSError: [WinError 1114] 动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by mazhichong** [yvquanli/BGNN#1]
I encountered some problems in the process of operation, and would like to consult.
OSError: [WinError 1114] 动态链接库(DLL)初始化例程失败。

**Comment by yvquanli** [comment]
应该是你环境没配置好

**Comment by yvquanli** [comment]
linux is a better choice

**Comment by mazhichong** [comment]
我环境配置好之后，出现了新的问题，想向您请教一下
报错1：
gpu = int(sys.argv[2])&nbsp; &nbsp;
IndexError: list index out of range



报错2：
self.device = torch.device("cuda:{}".format(option['cuda_devices'][0])
TypeError: 'NoneType' object is not subscriptable


请问您这两个问题是怎么解决的呢？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yvquanli/BGNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月21日(星期四) 下午5:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yvquanli/BGNN] OSError: [WinError 1114] 动态链接库(DLL)初始化例程失败。 (#1)





 
应该是你环境没配置好
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yvquanli** [comment]
报错1：
gpu = int(sys.argv[2])&nbsp; &nbsp;
IndexError: list index out of range
解决方案：sys.argv[2]，说明需要两个参数，你没有输入参数，所以它报错了，
你在python xx.py arg1 arg 2.


报错2：
self.device = torch.device("cuda:{}".format(option['cuda_devices'][0])
TypeError: 'NoneType' object is not subscriptable
解决方案：option['cuda_devices'][0]，说明你的option['cuda_devices'][0]为None ，你要设置一下

mazhichong ***@***.***> 于2021年10月21日周四 下午7:56写道：

**Comment by sjhsbhqf** [comment]
@mazhichong 你好，你的环境是怎么配置的呢？？？

**Comment by yvquanli** [comment]
你试试linux下使用如下进行配置

    conda create -n GLAM python=3.8 rdkit -c conda-forge --yes
    conda activate GLAM
    conda install pytorch=1.9.0 cudatoolkit=11.1 -c pytorch -c conda-forge --yes
    CUDA=cu111
    TORCH=1.9.0
    pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html 
    pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html 
    pip install torch-geometric==1.7.2

**Comment by sjhsbhqf** [comment]
@yvquanli 你好，非常感谢，因为我是Windows系统，没办法尝试这些了。

不过，我现在已经解决了这个问题，详情看我总结的文章：https://blog.csdn.net/PSpiritV/article/details/123742575

非常感谢！！！

**Comment by yvquanli** [comment]
好的，没问题
